import type { SiteLanguage } from "../sitePreferences";

export const downloadUrl = "https://github.com/anderbggo/GooglePhotosMatcher/releases/download/v3.0/GPMatcher.exe";
export const sourceUrl = "https://github.com/anderbggo/GooglePhotosMatcher";
export const privacyPath = "/gpmatcher/privacy/";
export const contributePath = "/contribute/";

export const text = {
  es: {
    skip: "Ir al contenido",
    productNav: "Cómo funciona",
    privacyNav: "Privacidad",
    language: "Idioma",
    theme: "Tema",
    light: "Modo claro",
    dark: "Modo oscuro",
    version: "v3.0 · Windows de 64 bits",
    lead: "Devuelve a tus fotos y vídeos de Google Fotos (descargados desde Takeout) sus fechas, ubicación y otros metadatos. En tu ordenador, sin subir tu biblioteca a ningún servidor.",
    download: "Descargar",
    downloadNote: "Gratis. Sin anuncios. Sin instalación.",
    source: "Ver código en GitHub",
    screenLightAlt: "Google Photos Matcher v3.0 en modo claro, con la interfaz en inglés y el resumen de una restauración.",
    screenDarkAlt: "Google Photos Matcher v3.0 en modo oscuro, con la interfaz en español y el resumen de una restauración.",
    screenLightCaption: "La app en modo claro · Interfaz en inglés",
    screenDarkCaption: "La app en modo oscuro · Interfaz en español",
    problemEyebrow: "De Takeout a tu biblioteca",
    problemTitle: "Tus fotos, con sus datos de nuevo.",
    problemIntro: "Google Takeout puede guardar parte de los metadatos en archivos JSON separados de las fotos y los vídeos. GPMatcher encuentra sus parejas y escribe esos datos en los archivos multimedia para que tu biblioteca vuelva a tener contexto.",
    photoLabel: "Tu foto o vídeo",
    jsonLabel: "Sus metadatos",
    resultLabel: "Metadatos restaurados",
    resultCaption: "Fecha, ubicación y descripción, si están en el JSON.",
    features: [
      { title: "Fechas de captura", body: "Recupera la fecha de tus recuerdos a partir de los datos de Takeout." },
      { title: "Ubicación y descripción", body: "Restaura las coordenadas GPS y las descripciones disponibles en cada JSON." },
      { title: "Coincidencias claras", body: "Reconoce duplicados y nombres especiales. Si hay varias parejas posibles, no adivina." },
      { title: "Una vista previa primero", body: "Revisa el plan sin modificar ni mover tus fotos y vídeos." },
    ],
    workflowEyebrow: "Tres pasos",
    workflowTitle: "Del archivo exportado a tus recuerdos.",
    workflowIntro: "No necesitas conectar tu cuenta de Google ni instalar Python para usar el ejecutable de Windows.",
    takeout: "Abrir Google Takeout",
    steps: [
      { title: "Exporta y prepara", body: "Descarga tus datos de Google Photos desde Takeout. Extrae todos los ZIP, conserva los JSON junto a sus fotos y haz una copia de seguridad." },
      { title: "Revisa las parejas", body: "Abre GPMatcher, selecciona la carpeta de Takeout y pulsa Vista previa. También se analizan las subcarpetas, sin modificar los archivos multimedia." },
      { title: "Restaura los metadatos", body: "Pulsa Restaurar y confirma el aviso. La app escribe los metadatos y organiza los resultados; puedes cancelar después de que termine el archivo en curso." },
    ],
    backupTitle: "Antes de restaurar, guarda una copia.",
    backupBody: "La restauración modifica y mueve los originales y elimina los JSON de las coincidencias completadas. No hay copia automática ni opción de deshacer. Un fallo de escritura puede dejar parte de los metadatos modificados.",
    resultsTitle: "Dónde queda cada archivo.",
    resultsIntro: "Las carpetas de resultados conservan la estructura de subcarpetas de tu exportación. Los resultados existentes no se sobrescriben.",
    matchedBody: "Las fotos y los vídeos restaurados, incluidas las versiones editadas de las fotos.",
    editedBody: "Las versiones originales de las fotos editadas, también con sus metadatos restaurados.",
    resultsNote: "Los archivos con errores o sin pareja y sus JSON permanecen en su carpeta original. Los JSON de restauraciones completadas se eliminan. El informe CSV recoge solo los errores; los contadores muestran el resumen completo.",
    privacyEyebrow: "Procesamiento local",
    privacyTitle: "Tu biblioteca se queda contigo.",
    privacyIntro: "GPMatcher lee tu exportación y restaura sus metadatos en tu ordenador. El desarrollador no recibe tus fotos, vídeos ni archivos JSON a través de la aplicación.",
    privacyLink: "Leer la política de privacidad",
    principles: [
      { title: "Sin subidas", body: "Tus archivos no se envían a una nube para restaurarlos." },
      { title: "Sin cuenta", body: "No pide credenciales ni acceso a tu cuenta de Google." },
      { title: "Sin telemetría", body: "La app no envía estadísticas de uso ni informes de tu biblioteca." },
    ],
    faqTitle: "Preguntas frecuentes",
    faqs: [
      { question: "¿Qué formatos puedo restaurar?", answer: "JPEG/JPG, HEIC/HEIF, PNG, WebP, TIFF/TIF y vídeos MP4, MOV, 3GP y M4V. ExifTool está incluido en el ejecutable de Windows. Los MKV se detectan, pero no se restauran porque ExifTool no puede escribir sus metadatos." },
      { question: "¿Funciona en macOS o Linux?", answer: "La descarga de esta página es un ejecutable para Windows de 64 bits. Para otros sistemas puedes ejecutar el código Python del repositorio con Python 3.10 o posterior, Tkinter y ExifTool instalado por separado. Un archivo EXE no funciona de forma nativa en macOS o Linux." },
      { question: "¿Y las Live Photos?", answer: "Un vídeo acompañante sin su propio JSON solo se procesa si su identificador Apple coincide con el de la imagen. El nombre del archivo no basta. Los identificadores se conservan y se comprueban después de escribir; la compatibilidad con Apple Photos aún necesita validación con exportaciones reales en macOS." },
      { question: "¿Por qué algunos archivos no se restauran?", answer: "Si faltan metadatos, hay varias parejas posibles o los JSON son contradictorios, GPMatcher evita elegir a ciegas. Consulta el registro de actividad y los contadores. El CSV detalla solo los errores, no todos los archivos sin pareja. Si una escritura falla, recupera el original desde tu copia de seguridad cuando sea necesario." },
      { question: "¿Qué zona horaria se utiliza?", answer: "Las fechas se interpretan en la zona horaria local de tu ordenador. Los desfases EXIF y la conversión UTC de QuickTime se actualizan de forma coherente, pero Takeout no siempre incluye la zona horaria original de la captura." },
      { question: "¿Vista previa cambia mis fotos?", answer: "No modifica ni mueve fotos o vídeos y no elimina sus JSON. Sí puede generar un informe local; las preferencias de idioma y tema también se guardan en tu perfil de usuario. La restauración real requiere confirmar el aviso de copia de seguridad." },
    ],
    creditsEyebrow: "Código y comunidad",
    creditsTitle: "Un proyecto abierto, hecho entre varios.",
    creditsIntro: "Creado por anderbggo, con contribuciones de Kadawatcha, Golde2341 y MoonjunGong. El código y las notas de las versiones están disponibles en GitHub.",
    libraryRoles: ["Interfaz de escritorio", "Interfaz de usuario", "Metadatos de imágenes y vídeos", "Metadatos EXIF de JPEG", "Ejecutable portátil"],
    contributeTitle: "Gratis, también para tu próxima biblioteca.",
    contributeBody: "Si GPMatcher te ha sido útil, puedes apoyar el desarrollo o compartir una incidencia en el repositorio.",
    contributeLink: "Apoyar el proyecto",
    issues: "Informar de un problema",
    privacy: "Política de privacidad",
    home: "Inicio",
    independent: "Proyecto independiente, no afiliado con Google.",
    back: "Volver a Google Photos Matcher",
    policyTitle: "Política de privacidad",
    policyIntro: "Cómo Google Photos Matcher v3.0 y esta página web tratan tus archivos, metadatos y preferencias.",
    updated: "Última actualización: 5 de octubre de 2026",
    contents: "Contenido de la política",
  },
  en: {
    skip: "Skip to content",
    productNav: "How it works",
    privacyNav: "Privacy",
    language: "Language",
    theme: "Theme",
    light: "Light mode",
    dark: "Dark mode",
    version: "v3.0 · 64-bit Windows",
    lead: "Restore capture dates, locations and other metadata to your Google Photos (downloaded from Takeout) on your computer, without uploading your library to a server.",
    download: "Download",
    downloadNote: "Free. No ads. No installation.",
    source: "View source on GitHub",
    screenLightAlt: "Google Photos Matcher v3.0 in light mode, showing the English interface and a restoration summary.",
    screenDarkAlt: "Google Photos Matcher v3.0 in dark mode, showing the Spanish interface and a restoration summary.",
    screenLightCaption: "The app in light mode · English interface",
    screenDarkCaption: "The app in dark mode · Spanish interface",
    problemEyebrow: "From Takeout to your library",
    problemTitle: "Your photos, reunited with their metadata.",
    problemIntro: "Google Takeout can store some metadata in JSON files separately from your photos and videos. GPMatcher finds their matching media and writes that data back into the files, giving your library its context again.",
    photoLabel: "Your photo or video",
    jsonLabel: "Its metadata",
    resultLabel: "Restored metadata",
    resultCaption: "Date, location and description, when present in the JSON.",
    features: [
      { title: "Capture dates", body: "Recover the dates of your memories from your Takeout metadata." },
      { title: "Location and description", body: "Restore the GPS coordinates and descriptions available in each JSON." },
      { title: "Clear matches", body: "Recognizes duplicates and special filenames. When several matches are possible, it does not guess." },
      { title: "A preview first", body: "Review the plan without modifying or moving your photos and videos." },
    ],
    workflowEyebrow: "Three steps",
    workflowTitle: "From your export back to your memories.",
    workflowIntro: "You do not need to connect your Google account or install Python to use the Windows executable.",
    takeout: "Open Google Takeout",
    steps: [
      { title: "Export and prepare", body: "Download your Google Photos data from Takeout. Extract all ZIP archives, keep the JSON files alongside their media and make a backup." },
      { title: "Review the matches", body: "Open GPMatcher, select your Takeout folder and click Preview. Subfolders are scanned too, without changing your media files." },
      { title: "Restore the metadata", body: "Click Match and confirm the warning. The app writes the metadata and organizes the results; cancellation takes effect after the current file finishes." },
    ],
    backupTitle: "Before restoring, make a backup.",
    backupBody: "Restoration modifies and moves the originals and deletes the JSON files for completed matches. There is no automatic copy or undo. A failed write may leave some metadata changed.",
    resultsTitle: "Where each file ends up.",
    resultsIntro: "The output folders preserve your export’s subfolder structure. Existing output files are never overwritten.",
    matchedBody: "Restored photos and videos, including edited versions of photos.",
    editedBody: "The original versions of edited photos, also with their metadata restored.",
    resultsNote: "Files with errors or no match and their JSON stay in their original folders. JSON files for completed restorations are deleted. The CSV report lists errors only; the counters show the full summary.",
    privacyEyebrow: "Local processing",
    privacyTitle: "Your library stays with you.",
    privacyIntro: "GPMatcher reads your export and restores its metadata on your computer. The developer does not receive your photos, videos or JSON files through the application.",
    privacyLink: "Read the privacy policy",
    principles: [
      { title: "No uploads", body: "Your files are not sent to a cloud service for restoration." },
      { title: "No account", body: "No credentials or access to your Google account required." },
      { title: "No telemetry", body: "The app does not send usage statistics or reports about your library." },
    ],
    faqTitle: "Frequently asked questions",
    faqs: [
      { question: "Which formats can I restore?", answer: "JPEG/JPG, HEIC/HEIF, PNG, WebP, TIFF/TIF and MP4, MOV, 3GP and M4V videos. ExifTool is included in the Windows executable. MKV files are detected but not restored because ExifTool cannot write their metadata." },
      { question: "Does it work on macOS or Linux?", answer: "The download on this page is a 64-bit Windows executable. On other systems, you can run the repository’s Python source with Python 3.10 or newer, Tkinter and a separate ExifTool installation. An EXE does not run natively on macOS or Linux." },
      { question: "What about Live Photos?", answer: "A companion video without its own JSON is processed only if its Apple identifier matches the image’s identifier. A matching filename is not enough. Identifiers are preserved and checked after writing; compatibility with Apple Photos still needs validation on real exports in macOS." },
      { question: "Why are some files not restored?", answer: "If metadata is missing, several matches are possible or JSON files conflict, GPMatcher avoids guessing. Check the activity log and counters. The CSV lists errors only, not every unmatched file. If a write fails, recover the original from your backup when needed." },
      { question: "Which timezone is used?", answer: "Dates are interpreted in your computer’s local timezone. EXIF offsets and QuickTime UTC conversion are updated consistently, but Takeout does not always include the original capture timezone." },
      { question: "Does Preview change my photos?", answer: "It does not modify or move photos or videos, or delete their JSON files. It can create a local report; language and theme preferences are also saved in your user profile. Actual restoration requires confirming the backup warning." },
    ],
    creditsEyebrow: "Code and community",
    creditsTitle: "An open project, built together.",
    creditsIntro: "Created by anderbggo, with contributions from Kadawatcha, Golde2341 and MoonjunGong. The source code and release notes are available on GitHub.",
    libraryRoles: ["Desktop interface", "User interface", "Image and video metadata", "JPEG EXIF metadata", "Portable executable"],
    contributeTitle: "Free, for your next library too.",
    contributeBody: "If GPMatcher has been useful to you, you can support its development or share an issue in the repository.",
    contributeLink: "Support the project",
    issues: "Report an issue",
    privacy: "Privacy policy",
    home: "Home",
    independent: "An independent project, not affiliated with Google.",
    back: "Back to Google Photos Matcher",
    policyTitle: "Privacy policy",
    policyIntro: "How Google Photos Matcher v3.0 and this website handle your files, metadata and preferences.",
    updated: "Last updated: October 5, 2026",
    contents: "Policy contents",
  },
} as const;

export const libraries = [
  { name: "Python / Tkinter", url: "https://docs.python.org/3/library/tkinter.html" },
  { name: "PySimpleGUI", url: "https://github.com/PySimpleGUI/PySimpleGUI" },
  { name: "ExifTool", url: "https://exiftool.org/" },
  { name: "piexif", url: "https://piexif.readthedocs.io/" },
  { name: "PyInstaller", url: "https://pyinstaller.org/" },
] as const;

type PrivacySection = {
  id: string;
  title: string;
  paragraphs: readonly string[];
  links?: readonly { label: string; url: string }[];
};

export const privacySections: Record<SiteLanguage, readonly PrivacySection[]> = {
  es: [
    {
      id: "scope", title: "1. Alcance y responsable",
      paragraphs: ["Google Photos Matcher (GPMatcher) es una aplicación de escritorio desarrollada por anderbggo para restaurar metadatos de exportaciones de Google Takeout. Esta política describe la versión 3.0 y esta web informativa. Es un proyecto independiente y no está afiliado con Google.", "La aplicación no requiere una cuenta, credenciales de Google ni acceso a Google Photos. Trabaja con la carpeta que seleccionas en tu ordenador."],
    },
    {
      id: "files", title: "2. Archivos y datos tratados localmente",
      paragraphs: ["GPMatcher lee fotos, vídeos y archivos JSON de la carpeta seleccionada y sus subcarpetas. Los JSON pueden contener nombres de archivo, fechas de captura, coordenadas GPS, descripciones y otros metadatos. Esos datos se utilizan localmente para identificar las parejas y restaurar los metadatos disponibles.", "La app no sube la biblioteca ni envía sus metadatos, estadísticas de uso o informes de errores al desarrollador. La restauración no necesita una conexión con un servidor."],
    },
    {
      id: "changes", title: "3. Cambios en los archivos y copia de seguridad",
      paragraphs: ["Restaurar modifica los archivos multimedia originales y mueve los resultados a MatchedMedia. Las versiones originales de fotos editadas se mueven a EditedRaw, también con sus metadatos restaurados. Ambas carpetas mantienen la estructura de subcarpetas. Los JSON asociados a restauraciones completadas se eliminan y los resultados existentes no se sobrescriben.", "Los archivos con errores o sin pareja y sus JSON permanecen en su ubicación original. Un fallo de escritura puede haber modificado parte de los metadatos. No hay copia de seguridad automática ni deshacer; conserva una copia de tu exportación antes de restaurar.", "Vista previa no modifica ni mueve fotos o vídeos y no elimina sus JSON. Puede generar un informe local."],
    },
    {
      id: "preferences", title: "4. Preferencias e informes",
      paragraphs: ["Las preferencias de idioma y tema se guardan en un archivo local del perfil de usuario. No se sincronizan con un servidor. El registro de actividad se muestra en la ventana y el informe CSV local contiene solo los errores, con los nombres o rutas de los archivos afectados y su causa.", "Los informes pueden revelar información de tu biblioteca. Revisa su contenido antes de compartirlos. Puedes eliminar las preferencias y los informes de tu ordenador; no existe una copia de estos datos en un servidor de GPMatcher."],
    },
    {
      id: "external", title: "5. Enlaces y servicios externos",
      paragraphs: ["Los enlaces de descarga y código abren GitHub; los enlaces a Google Takeout y apoyo pueden abrir otros servicios en tu navegador. Solo al acceder a esos servicios se aplica su propia política de privacidad. El ejecutable de Windows incluye ExifTool para procesar metadatos localmente; la aplicación no necesita descargarlo durante la restauración."],
      links: [{ label: "Privacidad de GitHub", url: "https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" }, { label: "Privacidad de Google", url: "https://policies.google.com/privacy?hl=es" }],
    },
    {
      id: "website", title: "6. Privacidad de esta web",
      paragraphs: ["Esta web utiliza el almacenamiento local del navegador para recordar tu idioma y tema, compartidos con las otras páginas de anderbggo.github.io. No incorpora analítica, anuncios, cookies de seguimiento ni formularios que reciban tu biblioteca. Las tipografías y las imágenes se sirven desde la propia web.", "La web se aloja en GitHub Pages. GitHub puede tratar información técnica de las visitas, como la dirección IP y datos de la petición, conforme a su propia política de privacidad. La descarga del ejecutable también se realiza desde GitHub. Puedes borrar las preferencias de esta web eliminando sus datos locales en el navegador."],
      links: [{ label: "Información sobre GitHub Pages", url: "https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages" }],
    },
    {
      id: "contact", title: "7. Contacto y cambios en la política",
      paragraphs: ["Puedes contactar con anderbggo mediante el repositorio de GitHub para dudas o incidencias de privacidad. Las incidencias son públicas: no adjuntes fotos personales, ubicaciones, JSON o informes sin revisar y ocultar los datos sensibles.", "La política puede actualizarse para reflejar cambios en la app o en esta web. La fecha que aparece al principio identifica su última revisión."],
      links: [{ label: "Contactar en GitHub", url: `${sourceUrl}/issues` }],
    },
  ],
  en: [
    {
      id: "scope", title: "1. Scope and developer",
      paragraphs: ["Google Photos Matcher (GPMatcher) is a desktop application developed by anderbggo to restore metadata from Google Takeout exports. This policy covers version 3.0 and this informational website. It is an independent project and is not affiliated with Google.", "The app does not require an account, Google credentials or access to Google Photos. It works with the folder you select on your computer."],
    },
    {
      id: "files", title: "2. Files and data processed locally",
      paragraphs: ["GPMatcher reads photos, videos and JSON files in the selected folder and its subfolders. JSON files can contain filenames, capture dates, GPS coordinates, descriptions and other metadata. This information is used locally to identify matching media and restore the available metadata.", "The app does not upload your library or send its metadata, usage statistics or error reports to the developer. Restoration does not require a connection to a server."],
    },
    {
      id: "changes", title: "3. File changes and backups",
      paragraphs: ["Match modifies the original media files and moves the results into MatchedMedia. Original versions of edited photos move into EditedRaw, also with their metadata restored. Both folders preserve the subfolder structure. JSON files associated with completed restorations are deleted, and existing output files are never overwritten.", "Files with errors or no match and their JSON stay in their original locations. A failed write may have changed some metadata. There is no automatic backup or undo; keep a copy of your export before restoring.", "Preview does not modify or move photos or videos, or delete their JSON. It can create a local report."],
    },
    {
      id: "preferences", title: "4. Preferences and reports",
      paragraphs: ["Language and theme preferences are saved in a local file in your user profile. They are not synchronized with a server. The activity log is shown in the app window, and the local CSV report contains errors only, including the names or paths of affected files and the cause.", "Reports can reveal information about your library. Review their contents before sharing. You can delete preferences and reports from your computer; GPMatcher has no server-side copy of this data."],
    },
    {
      id: "external", title: "5. External links and services",
      paragraphs: ["Download and source links open GitHub; Google Takeout and support links may open other services in your browser. Those services’ own privacy policies apply when you access them. The Windows executable includes ExifTool for local metadata processing; the app does not need to download it during restoration."],
      links: [{ label: "GitHub privacy statement", url: "https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" }, { label: "Google privacy policy", url: "https://policies.google.com/privacy?hl=en" }],
    },
    {
      id: "website", title: "6. This website’s privacy",
      paragraphs: ["This website uses browser local storage to remember your language and theme, shared with the other anderbggo.github.io pages. It does not include analytics, ads, tracking cookies or forms that receive your library. Fonts and images are served from this website itself.", "This website is hosted on GitHub Pages. GitHub may process technical visitor information, such as IP addresses and request data, under its own privacy policy. The executable download is also served by GitHub. You can remove this website’s preferences by clearing its local browser data."],
      links: [{ label: "About GitHub Pages", url: "https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages" }],
    },
    {
      id: "contact", title: "7. Contact and policy changes",
      paragraphs: ["You can contact anderbggo through the GitHub repository with privacy questions or concerns. Issues are public: do not attach personal photos, locations, JSON files or reports without reviewing them and removing sensitive information.", "This policy may be updated to reflect changes to the app or this website. The date at the top identifies the latest revision."],
      links: [{ label: "Contact on GitHub", url: `${sourceUrl}/issues` }],
    },
  ],
};